use etl;
#names of all patients from database

select name from healthcare;

#Unique medical conditions

select distinct(medical_condition) from healthcare;

#Find the total number of doctors in the system

select count(distinct(doctor)) from healthcare;

#Retrieve the details of all female patients.

select * from healthcare where gender="Female";

#Average age of patients in database

select round(avg(age)) as Average_age from healthcare;

#Identify the patients who have more than one medical condition.

select name,count(medical_condition)as count1 
from healthcare 
group by name 
having count1>1;

#names of doctor

select distinct(doctor) from healthcare;

# most common medical conditions

select medical_condition,count(medical_condition) as count 
from healthcare 
group by medical_condition 
order by count desc;

#patients who are above 60 and have diabetes

select * 
from healthcare 
where age>60 and medical_condition="Diabetes";

#Calculate the total revenue generated by the healthcare system. 

select sum(billing_amount) as Total_revenue 
from healthcare;

#Find the doctor with the oldest patient.

select doctor,age 
from healthcare 
where age=(select max(age) from healthcare);

#find the avrage duration of medical visists
select avg(duration) from healthcare;

#Give the names of patients whose name starts with A.

select * from healthcare where name like"a%";

#How many male and female patients are there in dataset.

select gender, count(*) 
from healthcare 
group by gender;

#how many patients are normal

select  count(*) as count 
from healthcare 
where test_results="normal";

#how many patients are abnormal or Inconclusive.

select count(*)as count 
from healthcare 
where test_results="abnormal" 
or test_results="inconclusive";

#how many patients of blood group AB+ are there of age above 52. 

select count(*) as patient_count 
from healthcare 
where blood_type="AB+" and age>52;

# how many patients have paid the bill above 24890.

select count(*) as patient_count 
from healthcare 
where billing_amount>24890;

#what are the names of patients having Asthma.

select name 
from healthcare 
where medical_condition="Asthma";

#how many patients have cancer
select count(name) 
from healthcare 
where medical_condition="cancer";

# what are the names and blood groups of patients admitted to room no. 292

select name,blood_type 
from healthcare 
where room_number=292;

#how many males have Arthritis
select count(name) 
from healthcare 
where medical_condition="Arthritis";

# How many patients were admitted to Harris and Sons hospital.
select count(*) 
from healthcare 
where hospital="Harris and sons";

#what are the names of patients whose Insurance Provider are Cigna

select name
from healthcare 
where insurance_provider="cigna";

#Name the Medical Condition having patients whose ages is greater than average age
select distinct(medical_condition) 
from healthcare 
where age>(select avg(age) from healthcare);

